server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true