server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker
        - eth.*
        - lo
      preferredNetworks:
        - 10.0.0
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true