server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        enabled: true
        lower-case-service-id: true
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url: http://localhost:8761/eureka**